[theme]
primaryColor = "#E60028"                 # Rouge SG
backgroundColor = "#F5F5F5"              # Gris tr√®s clair, pas noir
secondaryBackgroundColor = "#FFFFFF"     # Blanc
textColor = "#1A1A1A"                    # Noir doux
font = "sans serif"
